# Generated by Django 6.0.5 on 2026-05-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershippayment',
            old_name='provider_event_id',
            new_name='stripe_event_id',
        ),
        migrations.RemoveField(
            model_name='membershippayment',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='membershipplan',
            name='paypal_plan_id',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='payment_provider',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='paypal_subscription_id',
        ),
        migrations.AddField(
            model_name='usermembership',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('past_due', 'Past Due'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
