# Generated by Django 6.0.5 on 2026-05-20 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_rename_provider_event_id_membershippayment_stripe_event_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('past_due', 'Past Due'), ('paused', 'Paused'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='PlanSwitchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('credit_applied', models.DecimalField(decimal_places=2, max_digits=8)),
                ('switched_at', models.DateTimeField(auto_now_add=True)),
                ('from_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='switches_from', to='memberships.membershipplan')),
                ('to_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='switches_to', to='memberships.membershipplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
