# Generated by Django 6.0.5 on 2026-05-21 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_alter_usermembership_status_planswitchrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipplan',
            name='stripe_price_id',
        ),
    ]
