# Generated by Django 6.0.5 on 2026-05-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('deliver', 'Deliver'), ('delivered', 'Delivered'), ('deliverd', 'Deliverd')], default='pending', max_length=20),
        ),
    ]
